src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'array')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 100)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 100)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $pseudo;

    #[ORM\Column(type: 'datetime', options: ['default'=> 'CURRENT_TIMESTAMP'])]
    private $created_at;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: UsersProfile::class, cascade: ['persist', 'remove'])]
    private $usersProfile;

    #[ORM\OneToMany(mappedBy: 'auteur', targetEntity: Article::class)]
    private $articles;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: CarnetVoyage::class)]
    private $carnetVoyages;

    public function __construct()
    {
        $this->created_at =  new \DateTime();
        $this->articles = new ArrayCollection();
        $this->carnetVoyages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string |null
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUsersProfile(): ?UsersProfile
    {
        return $this->usersProfile;
    }

    public function setUsersProfile(?UsersProfile $usersProfile): self
    {
        // unset the owning side of the relation if necessary
        if ($usersProfile === null && $this->usersProfile !== null) {
            $this->usersProfile->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($usersProfile !== null && $usersProfile->getUser() !== $this) {
            $usersProfile->setUser($this);
        }

        $this->usersProfile = $usersProfile;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setAuteur($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuteur() === $this) {
                $article->setAuteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CarnetVoyage>
     */
    public function getCarnetVoyages(): Collection
    {
        return $this->carnetVoyages;
    }

    public function addCarnetVoyage(CarnetVoyage $carnetVoyage): self
    {
        if (!$this->carnetVoyages->contains($carnetVoyage)) {
            $this->carnetVoyages[] = $carnetVoyage;
            $carnetVoyage->setUsers($this);
        }

        return $this;
    }

    public function removeCarnetVoyage(CarnetVoyage $carnetVoyage): self
    {
        if ($this->carnetVoyages->removeElement($carnetVoyage)) {
            // set the owning side to null (unless already changed)
            if ($carnetVoyage->getUsers() === $this) {
                $carnetVoyage->setUsers(null);
            }
        }

        return $this;
    }
}

src/Controller/RedacteurCarnetVoyageController.php
<?php

namespace App\Controller;

use App\Entity\CarnetVoyage;
use App\Form\CarnetVoyage2Type;
use App\Repository\CarnetVoyageRepository;
use http\Client\Curl\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/redacteur/carnet/voyage')]
class RedacteurCarnetVoyageController extends AbstractController
{
    #[Route('/', name: 'app_redacteur_carnet_voyage_index', methods: ['GET'])]
    public function index(CarnetVoyageRepository $carnetVoyageRepository): Response
    {
        return $this->render('redacteur_carnet_voyage/index.html.twig', [
            'carnet_voyages' => $carnetVoyageRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_redacteur_carnet_voyage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CarnetVoyageRepository $carnetVoyageRepository): Response
    {
        $carnetVoyage = new CarnetVoyage();
        $user = $this->getUser();

        $form = $this->createForm(CarnetVoyage2Type::class, $carnetVoyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $carnetVoyage->setUsers($user); // faux positif
            $carnetVoyage->setCreatedAt(new \DateTimeImmutable());
            $carnetVoyage->setUpdateAt(new \DateTimeImmutable());
            $carnetVoyageRepository->add($carnetVoyage);
            return $this->redirectToRoute('app_redacteur_carnet_voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('redacteur_carnet_voyage/new.html.twig', [
            'carnet_voyage' => $carnetVoyage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_redacteur_carnet_voyage_show', methods: ['GET'])]
    public function show(CarnetVoyage $carnetVoyage): Response
    {
        return $this->render('redacteur_carnet_voyage/show.html.twig', [
            'carnet_voyage' => $carnetVoyage,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_redacteur_carnet_voyage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CarnetVoyage $carnetVoyage, CarnetVoyageRepository $carnetVoyageRepository): Response
    {
        $form = $this->createForm(CarnetVoyage2Type::class, $carnetVoyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $carnetVoyageRepository->add($carnetVoyage);
            return $this->redirectToRoute('app_redacteur_carnet_voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('redacteur_carnet_voyage/edit.html.twig', [
            'carnet_voyage' => $carnetVoyage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_redacteur_carnet_voyage_delete', methods: ['POST'])]
    public function delete(Request $request, CarnetVoyage $carnetVoyage, CarnetVoyageRepository $carnetVoyageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$carnetVoyage->getId(), $request->request->get('_token'))) {
            $carnetVoyageRepository->remove($carnetVoyage);
        }

        return $this->redirectToRoute('app_redacteur_carnet_voyage_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/redacteur_carnet_voyage/_delete_form.html.twig
<form method="post" action="{{ path('app_redacteur_carnet_voyage_delete', {'id': carnet_voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carnet_voyage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/redacteur_carnet_voyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/redacteur_carnet_voyage/edit.html.twig
{% extends 'redacteur.html.twig' %}

{% block title %}tout les  Carnets de Voyage{% endblock %}

{% block body %}
    <h1>Edit CarnetVoyage</h1>

    {{ include('redacteur_carnet_voyage/_form.html.twig', {'button_label': 'Mettre a jour'}) }}

    <a href="{{ path('app_redacteur_carnet_voyage_edit') }}">retour a la liste</a>

    {{ include('redacteur_carnet_voyage/_delete_form.html.twig') }}
{% endblock %}

templates/redacteur_carnet_voyage/index.html.twig
{% extends 'redacteur.html.twig' %}

{% block title %}CarnetVoyage index{% endblock %}

{% block body %}
    <h1>CarnetVoyage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>CreatedAt</th>
                <th>UpdateAt</th>
                <th>Slug</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for carnet_voyage in carnet_voyages %}
            <tr>
                <td>{{ carnet_voyage.id }}</td>
                <td>{{ carnet_voyage.title }}</td>
                <td>{{ carnet_voyage.createdAt ? carnet_voyage.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ carnet_voyage.updateAt ? carnet_voyage.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ carnet_voyage.slug }}</td>
                <td>
                    <a href="{{ path('app_redacteur_carnet_voyage_show', {'id': carnet_voyage.id}) }}">Voir</a>
                    <a href="{{ path('app_redacteur_carnet_voyage_edit', {'id': carnet_voyage.id}) }}">Édition</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_redacteur_carnet_voyage_new') }}">Ajouter un nouveau"</a>
{% endblock %}

templates/redacteur_carnet_voyage/new.html.twig
{% extends 'redacteur.html.twig' %}

{% block title %}Nouveau carnet de voyage{% endblock %}

{% block body %}
    <h1>Créer un nouveau carnet de voyage</h1>

    {{ include('redacteur_carnet_voyage/_form.html.twig') }}

    <a href="{{ path('app_redacteur_carnet_voyage_index') }}">Retour a mon espace</a>
{% endblock %}

templates/redacteur_carnet_voyage/show.html.twig
{% extends 'redacteur.html.twig' %}

{% block title %}CarnetVoyage{% endblock %}

{% block body %}
    <h1>CarnetVoyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ carnet_voyage.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ carnet_voyage.title }}</td>
            </tr>
            <tr>
                <th>contenue</th>
                <td>{{ carnet_voyage.Content }}</td>
            </tr>
            <tr>
                <th>Thumbnail</th>
                <td>{{ carnet_voyage.thumbnail }}</td>
            </tr>
            <tr>
                <th>ImageContent</th>
                <td>{{ carnet_voyage.imageContent }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ carnet_voyage.createdAt ? carnet_voyage.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdateAt</th>
                <td>{{ carnet_voyage.updateAt ? carnet_voyage.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ carnet_voyage.slug }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_redacteur_carnet_voyage_index') }}">back to list</a>

    <a href="{{ path('app_redacteur_carnet_voyage_edit', {'id': carnet_voyage.id}) }}">edit</a>

    {{ include('redacteur_carnet_voyage/_delete_form.html.twig') }}
{% endblock %}