src/Entity/CarnetVoyage.php
<?php

namespace App\Entity;

use App\Repository\CarnetVoyageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;


#[ORM\Entity(repositoryClass: CarnetVoyageRepository::class)]
#[Vich\Uploadable]

class CarnetVoyage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $Content;

    #[Vich\UploadableField(mapping: 'carnet_image', fileNameProperty: 'thumbnail')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', length: 255)]
    private  $thumbnail;


    #[Vich\UploadableField(mapping: 'carnet_image', fileNameProperty: 'imageContent')]
    private ?File $imageContentFile = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private  $imageContent;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updateAt;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: 'carnetVoyages')]
    private $users;

    #[ORM\Column(type: 'string', length: 100, unique: true)]
    #[Gedmo\Slug(fields:['title'])]
    private $slug;

    #[ORM\ManyToOne(targetEntity: Countries::class, inversedBy: 'carnetVoyages')]
    #[ORM\JoinColumn(nullable: false)]
    private $country;

    #[ORM\ManyToOne(targetEntity: Parcours::class, inversedBy: 'carnetVoyages')]
    private $parcour;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }/**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updateAt = new \DateTimeImmutable();
        }
    }

    public function setThumbnail(string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageContentFile(): ?File
    {
        return $this->imageContentFile;
    }
    /**
     * @param File|null $imageContentFile
     */
    public function setImageContentFile(?File $imageContentFile): void
    {
        if (null !== $imageContentFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updateAt = new \DateTimeImmutable();
        }
        $this->imageContentFile = $imageContentFile;
    }

    public function getImageContent(): ?string
    {
        return $this->imageContent;
    }

    public function setImageContent(?string $imageContent): self
    {
        $this->imageContent = $imageContent;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeImmutable $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }/**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    public function getCountry(): ?Countries
    {
        return $this->country;
    }

    public function setCountry(?Countries $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getParcour(): ?Parcours
    {
        return $this->parcour;
    }

    public function setParcour(?Parcours $parcour): self
    {
        $this->parcour = $parcour;

        return $this;
    }
}

src/Entity/UsersProfile.php
<?php

namespace App\Entity;

use App\Repository\UsersProfileRepository;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use JetBrains\PhpStorm\Internal\LanguageLevelTypeAware;
use Serializable;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: UsersProfileRepository::class)]
#[Vich\Uploadable]

class UsersProfile implements Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\OneToOne(inversedBy: 'usersProfile', targetEntity: Users::class, cascade: ['persist', 'remove'])]
    private $user;

    #[ORM\Column(type: 'text', nullable: true)]
    private $biography;

    #[Vich\UploadableField(mapping: 'avatar_image', fileNameProperty: 'avatar')]
    private ?File $avatarFile = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $avatar;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $url;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    /**
     * @return File|null
     */
    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    /**
     * @param File|null $avatarFile
     */
    public function setAvatarFile(?File $avatarFile): void
    {
        if (null !== $avatarFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
        $this->createdAt = new \DateTimeImmutable();
        }
        $this->avatarFile = $avatarFile;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function serialize()
    {
        // TODO: Implement serialize() method.
    }

    public function unserialize(string $data)
    {
        // TODO: Implement unserialize() method.
    }
}

src/Form/UsersProfileType.php
<?php

namespace App\Form;

use App\Entity\UsersProfile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;
use phpDocumentor\Reflection\File;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;



class UsersProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('biography')


            ->add('avatar', HiddenType::class, [
                'attr' => [
                    'placeholder' =>    "avatar"
                ]
            ])

            ->add('avatarFile', VichFileType::class, [
                'label'=> "ajouter un avatar",
                'required'=>false,
                'allow_delete' => true,
                'delete_label' => '...',
                'download_label' => '...',
                'download_uri' => '...',
                'asset_helper'=> true,
            ])






            ->add('url')


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UsersProfile::class,
        ]);
    }
}

src/Controller/UsersProfileController.php
<?php

namespace App\Controller;

use App\Entity\UsersProfile;
use App\Form\UsersProfileType;
use App\Repository\ArticleRepository;
use App\Repository\UsersProfileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



#[Route('/users/profile')]
class UsersProfileController extends AbstractController
{


    #[Route('/{id}', name: 'app_users_profile_show', methods: ['GET'])]
    public function show(UsersProfile $usersProfile, ArticleRepository $articleRepository ): Response
    {

        if($this->getUser() == $usersProfile->getUser()){

            $canEdit = true;
        }

        return $this->render('users_profile/show.html.twig', [
            'users_profile' => $usersProfile,
            'can_edit' => $canEdit
        ]);
    }

    #[Route('/{id}/edit', name: 'app_users_profile_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UsersProfile $usersProfile, UsersProfileRepository $usersProfileRepository): Response
    {
            //controle que l'utlitisateur actuel est le propriétaire du profil
        if ($this->getUser() != $usersProfile->getUser()) { 
            $this->addFlash('warning', "Opération interdite");
            
            //redirection sur la page d'accueil 
            return $this->redirectToRoute('app_users_profile_show');
        }

        $form = $this->createForm(UsersProfileType::class, $usersProfile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $usersProfileRepository->add($usersProfile);
            return $this->redirectToRoute('main', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('users_profile/edit.html.twig', [
            'users_profile' => $usersProfile,
            'form' => $form,
        ]);
    }

}

templates/users_profile/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/users_profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}

    <section class="conten_article">
        <article class="article-center">
            <div class="wrapper">
                <div class="article-title">
                    <h1 class="title title_level_2"> Profile de {{ users_profile.user.pseudo }}</h1>

                    {{ include('users_profile/_form.html.twig', {'button_label': 'Update'}) }}

                </div>

            </div> ad

        <figure class="article-image">

            {% if users_profile.avatar %}

            {% else %}
                <img src="https://i.pravatar.cc/300" alt="" srcset="">

            {% endif %}

        </figure>

    </section>


    <a href="{{ path('main') }}">Retour a l'accueil</a>


{% endblock %}

templates/users_profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UsersProfile{% endblock %}

{% block body %}

<div class="main">

    <div class="main__container__wrapper">

        <section class="conten_article">
            <article class="article-center">
                <div class="wrapper">
                    <div class="article-title">
                        <h1 class="title title_level_3"> Profile de <span class="title_citation">{{ users_profile.user.pseudo }}</span> </h1>
                        <div class="article-text">
                            <h3 class="title title_level_4">{{ users_profile.user.lastname }}</h3>
                            <h3 class="title title_level_4">{{ users_profile.user.firstname }}</h3>
                            {% if users_profile.biography  %}

                                <p class="text paragraph__bold form-btn">Biographie</p>
                                <p class="text paragraph form-btn" > {{ users_profile.biography}}  </p>

                                    {% else %}
                                        <p class="text paragraph__bold form-btn">Pas de Bio</p>
                            {% endif   %}


                                <h4 class="title title_level_4">Rôles</h4>
                            {% for role in users_profile.user.roles %}
                                {% if role == "ROLE_ADMIN" %}
                                    <span class="paragraph"> Administrateur </span>
                                {% else %}
                                    <span class="paragraph"> Scribe </span>
                                {% endif %}

                            {% endfor %}
                        </div>
                    </div>

                        {% if app.user.id == users_profile.user.id %}
                    <button>

                        <a class="" href="{{ path('app_users_profile_edit', {'id': users_profile.user.id}) }}">Édition du profil</a>

                    </button>

                    {% endif %}

                </div>
            </article>

                <figure class="article-image">

                    {% if users_profile.avatar %}
                        <img src="{{  vich_uploader_asset( users_profile , 'avatarFile') }}" alt="" srcset="">

                        {% else %}
                            <img src="https://i.pravatar.cc/300" alt="" srcset="">

                    {% endif %}

                </figure>

        </section>

        {% if  users_profile.user.articles != null %}
                <h3 class="title title_level_4"> Liste des article de  {{ users_profile.user.lastname }}</h3>


            <section class="galery__article">

                {% if "ROLE_ADMIN" in app.user.roles %}

                 {% for article in users_profile.user.articles  %}
                    <div class="archive__card">
                        <img class="background_absolute" src="{{ article.thumbnail }}" alt="">
                        <div class="card_archive_content">
                            <h3 class="title title_level_3">{{ article.title }}</h3>
                            <small class="paragraph"></small>
                            <p class="paragraph">{{ article.content |u.truncate(30) }} ...</p>
                            <button><a href="{{ path('article_show', {'id': article.id}) }}"> lire la suite  </a>  </button>
                            <div class="info_article">
                                <small> écrit par <strong>{{ article.auteur.pseudo }}</strong> </small>
                                <small>{{ article.updateAt|date('d/m/Y') }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% elseif "ROLE_USER" in app.user.roles %}
                        {% for carnet in users_profile.user.carnetVoyages %}
                            <div class="archive__card">
                                <img class="background_absolute" src="{{  vich_uploader_asset(carnet, 'imageFile') }}" alt="">
                                <div class="card_archive_content">
                                    <h3 class="title title_level_3">{{ carnet.title }}</h3>
                                    <small class="paragraph"></small>
                                    <p class="paragraph">{{ carnet.content|u.truncate(30)|raw }} ...</p>
                                    <button><a href="{{ path('carnet_show', {'id': carnet.id}) }}"> lire la suite  </a>  </button>
                                    <div class="info_article">
                                        <small> ecrit par <strong>{{ carnet.users.pseudo }}</strong> </small>
                                        <small>{{ carnet.updateAt|date('d/m/Y') }}</small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                {% endif %}

            </section>
        {% endif %}



    </div>
</div>





{% endblock %}